spring:
  data:
    mongodb:
      database: Imagenes
      host: localhost
      port: 27017

  main:
    allow-bean-definition-overriding: true

server:
  port: 8090


feign:
  modulo:
    persona: ${URL_MODULO_PERSONA:localhost:8080}